### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by TurtleException** [TurtleException/TurtleCore#16]
Since #8 is basically outdated since #14, here is a new TODO list for the first stable version / release.

# Enhancements
- [ ] Create TurtleClient#shutdownNow()
- [ ] Create cache events (optional)
- [ ] Implement latest ping / retrieve ping methods
- [ ] Use constants for resource keys

# Debug
- [ ] Implement `AnnotationUtil#getAnnotation(Class<?>, AccessibleObject, Class<T>):<T extends Annotation>`

**Comment by TurtleException** [comment]
Also #21 (concept)
